--
--CREATE A DATABASE CALLED UNIVERSITY_DB
CREATE DATABASE UNIVERSITY_DB2;

USE  UNIVERSITY_DB;

--CREATE THE STUDENTS TABLE

CREATE TABLE STUDENTS(
Student_id INT IDENTITY PRIMARY KEY,
First_name VARCHAR (30),
Last_name VARCHAR (30),
Date_of_birth DATE,
Major VARCHAR (30)
);

SELECT*
FROM STUDENTS

 -- CREATE COURSES TABLE

 CREATE TABLE COURSES(
 Course_id INT IDENTITY PRIMARY KEY,
 Course_name VARCHAR (50),
 Department VARCHAR(50),
 Credit_hours TIME
 );

 SELECT*
 FROM COURSES

 CREATE THE ENROLLMENTS TABLE
 CREATE TABLE ENROLLMENTS(
 Enrollment_id INT IDENTITY PRIMARY KEY,
  Student_id INT REFERENCES STUDENTS(Student_id),
  course_id INT REFERENCES COURSES(course_id)
  );
